services:
  trading-front:
    build: ./trading-front
    container_name: trading-front
    restart: always
    ports:
      - "3000:3000"
    networks:
      - trading_network
    environment:
      - REACT_APP_API_URL=http://trading-admin:3000

  trading-admin:
    build: ./trading-admin
    container_name: trading-admin
    restart: always
    env_file:
      - ./trading-admin/.env
    ports:
      - "3001:3000"
    networks:
      - trading_network


  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - trading_network

networks:
  trading_network:
    driver: bridge
